baseurl: https://dysgu.netlify.app/
title: Fy Mlog Cymraeg
author: Rhian Davies
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  progressively: no
  sitename: Fy Mlog Cymraeg
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Adre
      url: /
      weight: 1
    - name: Am
      url: /am/
      weight: 2
    - name: Cyffyrddiad
      url: http://rhian.rbind.io/
      weight: 3
